#!/bin/bash

###########################
#
# Some fixes in the files
# generated by the export command
#
###########################

cd ../result || exit

for f in *.xml; do dos2unix -f "$f"; done

for f in *.xml; do perl -i -pe's/&//g' "$f"; done
for f in *.xml; do perl -i -pe's/@/_/g' "$f"; done

