spring.application.name=smbox
server.address=127.0.0.1
server.port=0
spring.datasource.url=jdbc:sqlite:${user.home}/smbox/data/smbox.db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
logging.file.name=${user.home}/smbox/smbox.log
